return {
  require("plugins.full.conform"),
  require("plugins.full.copilot"),
  require("plugins.full.database"),
  require("plugins.full.flash"),
  require("plugins.full.mason"),
  require("plugins.full.mason-lspconfig"),
  require("plugins.full.markdown"),
  require("plugins.full.mason-tool-installer"),
  require("plugins.full.neotest"),
  require("plugins.full.nvim-cmp"),
  require("plugins.full.nvim-dap"),
  require("plugins.full.octo"),
  require("plugins.full.persisted"),
  require("plugins.full.treesitter"),
}
