# Use terminal default fg/bg so VisiData matches your terminal background.
options.color_default = ''
options.color_default_hdr = 'bold'
options.color_bottom_hdr = 'underline'
options.color_column_sep = ''
options.color_menu = ''
options.color_menu_active = 'bold'
options.color_menu_spec = ''
options.color_menu_help = ''
options.color_status = 'bold'
options.color_top_status = ''
options.color_active_status = ''
options.color_inactive_status = ''
options.color_highlight_status = 'bold'
options.color_keystrokes = 'bold'
