set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

bind q choose-tree -Zs

bind s split-window -v
bind v split-window -h

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind l
bind l next-window
bind h previous-window

set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/bin/tmux-plugins/'

set -g prefix2 C-s
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'catppuccin/tmux'
source ~/.config/tmux/catppuccin.conf

source ~/.config/tmux/tmux-navigator.conf

run -b '~/bin/tmux-plugins/tpm/tpm'

