git:
  pagers:
    - pager: delta --paging=never --line-numbers
    - pager: delta --paging=never --line-numbers --side-by-side
gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#283457"
